# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 675)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.note_text = QtWidgets.QTextEdit(self.centralwidget)
        self.note_text.setObjectName("note_text")
        self.horizontalLayout_2.addWidget(self.note_text)
        self.instruments = QtWidgets.QVBoxLayout()
        self.instruments.setObjectName("instruments")
        self.notes_navigation = QtWidgets.QVBoxLayout()
        self.notes_navigation.setObjectName("notes_navigation")
        self.notes_label = QtWidgets.QLabel(self.centralwidget)
        self.notes_label.setObjectName("notes_label")
        self.notes_navigation.addWidget(self.notes_label)
        self.notes_list = QtWidgets.QListWidget(self.centralwidget)
        self.notes_list.setObjectName("notes_list")
        self.notes_navigation.addWidget(self.notes_list)
        self.notes_buttons = QtWidgets.QVBoxLayout()
        self.notes_buttons.setObjectName("notes_buttons")
        self.h_notes_buttons = QtWidgets.QHBoxLayout()
        self.h_notes_buttons.setObjectName("h_notes_buttons")
        self.create_note_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_note_button.setObjectName("create_note_button")
        self.h_notes_buttons.addWidget(self.create_note_button)
        self.delete_note_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_note_button.setObjectName("delete_note_button")
        self.h_notes_buttons.addWidget(self.delete_note_button)
        self.notes_buttons.addLayout(self.h_notes_buttons)
        self.save_note_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_note_button.setObjectName("save_note_button")
        self.notes_buttons.addWidget(self.save_note_button)
        self.notes_navigation.addLayout(self.notes_buttons)
        self.instruments.addLayout(self.notes_navigation)
        self.tags_navigation = QtWidgets.QVBoxLayout()
        self.tags_navigation.setObjectName("tags_navigation")
        self.tags_notes = QtWidgets.QLabel(self.centralwidget)
        self.tags_notes.setObjectName("tags_notes")
        self.tags_navigation.addWidget(self.tags_notes)
        self.tags_list = QtWidgets.QListWidget(self.centralwidget)
        self.tags_list.setObjectName("tags_list")
        self.tags_navigation.addWidget(self.tags_list)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.tags_navigation.addWidget(self.lineEdit)
        self.tag_buttons = QtWidgets.QVBoxLayout()
        self.tag_buttons.setObjectName("tag_buttons")
        self.h_tag_buttons = QtWidgets.QHBoxLayout()
        self.h_tag_buttons.setObjectName("h_tag_buttons")
        self.create_tag_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_tag_button.setObjectName("create_tag_button")
        self.h_tag_buttons.addWidget(self.create_tag_button)
        self.delete_tag_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_tag_button.setObjectName("delete_tag_button")
        self.h_tag_buttons.addWidget(self.delete_tag_button)
        self.tag_buttons.addLayout(self.h_tag_buttons)
        self.search_tag_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_tag_button.setObjectName("search_tag_button")
        self.tag_buttons.addWidget(self.search_tag_button)
        self.tags_navigation.addLayout(self.tag_buttons)
        self.instruments.addLayout(self.tags_navigation)
        self.horizontalLayout_2.addLayout(self.instruments)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Розумні замітки"))
        self.notes_label.setText(_translate("MainWindow", "Список заміток"))
        self.create_note_button.setText(_translate("MainWindow", "Створити замітку"))
        self.delete_note_button.setText(_translate("MainWindow", "Видалити замітку!"))
        self.save_note_button.setText(_translate("MainWindow", "Збереги замітку"))
        self.tags_notes.setText(_translate("MainWindow", "Список тегів"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введіть тег..."))
        self.create_tag_button.setText(_translate("MainWindow", "Додати до замітки"))
        self.delete_tag_button.setText(_translate("MainWindow", "Відкріпити від замітки"))
        self.search_tag_button.setText(_translate("MainWindow", "Шукати замітки по тегу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
